server.port: 8080
spring.application.name: site
eureka.instance.hostname: localhost
eureka.server.port: 8761
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
