server.port: 8090
spring.application.name: user-service

eureka.instance.hostname: localhost
eureka.server.port: 8761
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
spring.zipkin.base-url: http://${eureka.instance.hostname}:9411
