server.port: 8070
spring.application.name: config-server
eureka.instance.hostname: localhost
eureka.server.port: 8761
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
